### PR TITLE
Use black to format code, add support for poetry and pre-commit

### PR DESCRIPTION
**Pull request by dekoza**
This is mainly a cosmetic update for the codebase. [Black](https://github.com/psf/black/) is now a de-facto standard code formatter.

I added minimal config for [pre-commit](https://pre-commit.com/).

I also took the liberty of adding [poetry](https://python-poetry.org/docs/) support as it already uses `pyproject.toml` file used also by black and isort. And it's the best venv solution on the market.

### CODE REVIEW

**Comment by barrust** [comment]
How does the pre-commit work? Will it automatically black format the code or would one need to do something to set it up?

**Comment by dekoza** [comment]
@barrust you need to [set it up](https://pre-commit.com/#quick-start). After installing you need to run `pre-commit install` inside your local repo - this way it adds itself to local git hooks. Do bear in mind that each failure (e.g. black doing reformat) prevents commit from happening - just `git add` and `git commit` again (works best with `git commit -a`).

**Comment by dekoza** [comment]
I think I'll remove also setup.py :thinking:

**Comment by barrust** [comment]
I use the `setup.py` to build the library distribution and to run the tests.

**Comment by dekoza** [comment]
Not needed when using poetry.

**Comment by dekoza** [comment]
I also configure tox for running the tests on all supported python versions. Plus I also refactored some code. All coming up in next PR.

**Pull request merged**
